export enum INPUT_STATES {
  IDLE = "IDLE",
  START = "START",
  END = "END"
}

export enum TIME_SELECTED_STATES {
  NONE = "NONE",
  START = "START",
  END = "END"
}

export const PLAYER_STATES = {
  PLAYING: "PLAYING",
  INPUT_STATE: "INPUT_STATE",
  TAG_START_TIME: "TAG_START_TIME",
  TAG_END_TIME: "TAG_END_TIME",
  TAG_TIME_SELECTED: "TAG_TIME_SELECTED",
  TAG_CONTENT: "TAG_CONTENT"
}